proxies:
- name: Americas-01
  type: http
  server: 77.111.246.59
  port: 443
  username: 4EA6BFF24BB30BECB6450A316FD90589E34A94B3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJEbGtJUTFlSzRJY2xwX1FtNDNRb2JQQ3FnVkRaN3d1eG9TOVNSSGdVOHlJIiwieSI6Im1fTjVmVXlkaXpHN29iNkJKZnZ5eVoxVWtqY0RzYnFuNnZGS2FvNHhiSjAifX0.xwTL1gScBW7Pywfzd4nWHQcylkKs_jH21TPN0hdoiyymzZ1MCFV84A.WpDXbbhNRV1YzwHp.2OPkVib4oAhPRPGIbaDlWBREyN8mt2SKxwzq7SFDpi5ZVgqUvbJsZ3xMPPpIfrRwt42-mOKGDO80Im8nOY0en3nsq6LGhp90pjrZ4BjjIfXkX6CW-0wQMK5RhMrEUPC2yt6-I1SupN97EBJFb775s0_0z-hPmziwqi1ImKIrp8wHWlZZvD6JlN9Q_vWOMNRleAFjA5psavZlIrIHG5Cz6sJyu0o_GRJXoIKXSM1gQTJxgWX9tn59oecAylKqX08MaNfGXSiL2J1kBgKqvq4myP7eQSCR3dBoBXmiYXq5smCw80j4bc3Wjpnpip-bM0jABxqnORoAn0YtbZb9otFR2pzSlGYFYGFR3vD5mrE9MOFC3pm-TCHcllV36Sj0CxR0FkKzZ8tagfQ48cma3dLoHhiXCg0QHQRw8aF5l1N1cfH3czB7KRdaRTcZ6n5UYOa_4GuWDUsKCrfQ.HQcZZN98CzvA82QTgkleEw
  tls: true
  skip-cert-verify: true
  sni: am0.sec-tunnel.com
- name: Americas-02
  type: http
  server: 77.111.246.40
  port: 443
  username: 4EA6BFF24BB30BECB6450A316FD90589E34A94B3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJEbGtJUTFlSzRJY2xwX1FtNDNRb2JQQ3FnVkRaN3d1eG9TOVNSSGdVOHlJIiwieSI6Im1fTjVmVXlkaXpHN29iNkJKZnZ5eVoxVWtqY0RzYnFuNnZGS2FvNHhiSjAifX0.xwTL1gScBW7Pywfzd4nWHQcylkKs_jH21TPN0hdoiyymzZ1MCFV84A.WpDXbbhNRV1YzwHp.2OPkVib4oAhPRPGIbaDlWBREyN8mt2SKxwzq7SFDpi5ZVgqUvbJsZ3xMPPpIfrRwt42-mOKGDO80Im8nOY0en3nsq6LGhp90pjrZ4BjjIfXkX6CW-0wQMK5RhMrEUPC2yt6-I1SupN97EBJFb775s0_0z-hPmziwqi1ImKIrp8wHWlZZvD6JlN9Q_vWOMNRleAFjA5psavZlIrIHG5Cz6sJyu0o_GRJXoIKXSM1gQTJxgWX9tn59oecAylKqX08MaNfGXSiL2J1kBgKqvq4myP7eQSCR3dBoBXmiYXq5smCw80j4bc3Wjpnpip-bM0jABxqnORoAn0YtbZb9otFR2pzSlGYFYGFR3vD5mrE9MOFC3pm-TCHcllV36Sj0CxR0FkKzZ8tagfQ48cma3dLoHhiXCg0QHQRw8aF5l1N1cfH3czB7KRdaRTcZ6n5UYOa_4GuWDUsKCrfQ.HQcZZN98CzvA82QTgkleEw
  tls: true
  skip-cert-verify: true
  sni: am1.sec-tunnel.com
- name: Americas-03
  type: http
  server: 77.111.246.64
  port: 443
  username: 4EA6BFF24BB30BECB6450A316FD90589E34A94B3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJEbGtJUTFlSzRJY2xwX1FtNDNRb2JQQ3FnVkRaN3d1eG9TOVNSSGdVOHlJIiwieSI6Im1fTjVmVXlkaXpHN29iNkJKZnZ5eVoxVWtqY0RzYnFuNnZGS2FvNHhiSjAifX0.xwTL1gScBW7Pywfzd4nWHQcylkKs_jH21TPN0hdoiyymzZ1MCFV84A.WpDXbbhNRV1YzwHp.2OPkVib4oAhPRPGIbaDlWBREyN8mt2SKxwzq7SFDpi5ZVgqUvbJsZ3xMPPpIfrRwt42-mOKGDO80Im8nOY0en3nsq6LGhp90pjrZ4BjjIfXkX6CW-0wQMK5RhMrEUPC2yt6-I1SupN97EBJFb775s0_0z-hPmziwqi1ImKIrp8wHWlZZvD6JlN9Q_vWOMNRleAFjA5psavZlIrIHG5Cz6sJyu0o_GRJXoIKXSM1gQTJxgWX9tn59oecAylKqX08MaNfGXSiL2J1kBgKqvq4myP7eQSCR3dBoBXmiYXq5smCw80j4bc3Wjpnpip-bM0jABxqnORoAn0YtbZb9otFR2pzSlGYFYGFR3vD5mrE9MOFC3pm-TCHcllV36Sj0CxR0FkKzZ8tagfQ48cma3dLoHhiXCg0QHQRw8aF5l1N1cfH3czB7KRdaRTcZ6n5UYOa_4GuWDUsKCrfQ.HQcZZN98CzvA82QTgkleEw
  tls: true
  skip-cert-verify: true
  sni: am2.sec-tunnel.com
- name: Americas-04
  type: http
  server: 77.111.246.60
  port: 443
  username: 4EA6BFF24BB30BECB6450A316FD90589E34A94B3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJEbGtJUTFlSzRJY2xwX1FtNDNRb2JQQ3FnVkRaN3d1eG9TOVNSSGdVOHlJIiwieSI6Im1fTjVmVXlkaXpHN29iNkJKZnZ5eVoxVWtqY0RzYnFuNnZGS2FvNHhiSjAifX0.xwTL1gScBW7Pywfzd4nWHQcylkKs_jH21TPN0hdoiyymzZ1MCFV84A.WpDXbbhNRV1YzwHp.2OPkVib4oAhPRPGIbaDlWBREyN8mt2SKxwzq7SFDpi5ZVgqUvbJsZ3xMPPpIfrRwt42-mOKGDO80Im8nOY0en3nsq6LGhp90pjrZ4BjjIfXkX6CW-0wQMK5RhMrEUPC2yt6-I1SupN97EBJFb775s0_0z-hPmziwqi1ImKIrp8wHWlZZvD6JlN9Q_vWOMNRleAFjA5psavZlIrIHG5Cz6sJyu0o_GRJXoIKXSM1gQTJxgWX9tn59oecAylKqX08MaNfGXSiL2J1kBgKqvq4myP7eQSCR3dBoBXmiYXq5smCw80j4bc3Wjpnpip-bM0jABxqnORoAn0YtbZb9otFR2pzSlGYFYGFR3vD5mrE9MOFC3pm-TCHcllV36Sj0CxR0FkKzZ8tagfQ48cma3dLoHhiXCg0QHQRw8aF5l1N1cfH3czB7KRdaRTcZ6n5UYOa_4GuWDUsKCrfQ.HQcZZN98CzvA82QTgkleEw
  tls: true
  skip-cert-verify: true
  sni: am3.sec-tunnel.com
- name: Singapore-01
  type: http
  server: 77.111.245.16
  port: 443
  username: 4EA6BFF24BB30BECB6450A316FD90589E34A94B3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJEbGtJUTFlSzRJY2xwX1FtNDNRb2JQQ3FnVkRaN3d1eG9TOVNSSGdVOHlJIiwieSI6Im1fTjVmVXlkaXpHN29iNkJKZnZ5eVoxVWtqY0RzYnFuNnZGS2FvNHhiSjAifX0.xwTL1gScBW7Pywfzd4nWHQcylkKs_jH21TPN0hdoiyymzZ1MCFV84A.WpDXbbhNRV1YzwHp.2OPkVib4oAhPRPGIbaDlWBREyN8mt2SKxwzq7SFDpi5ZVgqUvbJsZ3xMPPpIfrRwt42-mOKGDO80Im8nOY0en3nsq6LGhp90pjrZ4BjjIfXkX6CW-0wQMK5RhMrEUPC2yt6-I1SupN97EBJFb775s0_0z-hPmziwqi1ImKIrp8wHWlZZvD6JlN9Q_vWOMNRleAFjA5psavZlIrIHG5Cz6sJyu0o_GRJXoIKXSM1gQTJxgWX9tn59oecAylKqX08MaNfGXSiL2J1kBgKqvq4myP7eQSCR3dBoBXmiYXq5smCw80j4bc3Wjpnpip-bM0jABxqnORoAn0YtbZb9otFR2pzSlGYFYGFR3vD5mrE9MOFC3pm-TCHcllV36Sj0CxR0FkKzZ8tagfQ48cma3dLoHhiXCg0QHQRw8aF5l1N1cfH3czB7KRdaRTcZ6n5UYOa_4GuWDUsKCrfQ.HQcZZN98CzvA82QTgkleEw
  tls: true
  skip-cert-verify: true
  sni: as0.sec-tunnel.com
- name: Finland-01
  type: http
  server: 77.111.247.80
  port: 443
  username: 4EA6BFF24BB30BECB6450A316FD90589E34A94B3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJEbGtJUTFlSzRJY2xwX1FtNDNRb2JQQ3FnVkRaN3d1eG9TOVNSSGdVOHlJIiwieSI6Im1fTjVmVXlkaXpHN29iNkJKZnZ5eVoxVWtqY0RzYnFuNnZGS2FvNHhiSjAifX0.xwTL1gScBW7Pywfzd4nWHQcylkKs_jH21TPN0hdoiyymzZ1MCFV84A.WpDXbbhNRV1YzwHp.2OPkVib4oAhPRPGIbaDlWBREyN8mt2SKxwzq7SFDpi5ZVgqUvbJsZ3xMPPpIfrRwt42-mOKGDO80Im8nOY0en3nsq6LGhp90pjrZ4BjjIfXkX6CW-0wQMK5RhMrEUPC2yt6-I1SupN97EBJFb775s0_0z-hPmziwqi1ImKIrp8wHWlZZvD6JlN9Q_vWOMNRleAFjA5psavZlIrIHG5Cz6sJyu0o_GRJXoIKXSM1gQTJxgWX9tn59oecAylKqX08MaNfGXSiL2J1kBgKqvq4myP7eQSCR3dBoBXmiYXq5smCw80j4bc3Wjpnpip-bM0jABxqnORoAn0YtbZb9otFR2pzSlGYFYGFR3vD5mrE9MOFC3pm-TCHcllV36Sj0CxR0FkKzZ8tagfQ48cma3dLoHhiXCg0QHQRw8aF5l1N1cfH3czB7KRdaRTcZ6n5UYOa_4GuWDUsKCrfQ.HQcZZN98CzvA82QTgkleEw
  tls: true
  skip-cert-verify: true
  sni: eu0.sec-tunnel.com
- name: Finland-02
  type: http
  server: 77.111.247.24
  port: 443
  username: 4EA6BFF24BB30BECB6450A316FD90589E34A94B3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJEbGtJUTFlSzRJY2xwX1FtNDNRb2JQQ3FnVkRaN3d1eG9TOVNSSGdVOHlJIiwieSI6Im1fTjVmVXlkaXpHN29iNkJKZnZ5eVoxVWtqY0RzYnFuNnZGS2FvNHhiSjAifX0.xwTL1gScBW7Pywfzd4nWHQcylkKs_jH21TPN0hdoiyymzZ1MCFV84A.WpDXbbhNRV1YzwHp.2OPkVib4oAhPRPGIbaDlWBREyN8mt2SKxwzq7SFDpi5ZVgqUvbJsZ3xMPPpIfrRwt42-mOKGDO80Im8nOY0en3nsq6LGhp90pjrZ4BjjIfXkX6CW-0wQMK5RhMrEUPC2yt6-I1SupN97EBJFb775s0_0z-hPmziwqi1ImKIrp8wHWlZZvD6JlN9Q_vWOMNRleAFjA5psavZlIrIHG5Cz6sJyu0o_GRJXoIKXSM1gQTJxgWX9tn59oecAylKqX08MaNfGXSiL2J1kBgKqvq4myP7eQSCR3dBoBXmiYXq5smCw80j4bc3Wjpnpip-bM0jABxqnORoAn0YtbZb9otFR2pzSlGYFYGFR3vD5mrE9MOFC3pm-TCHcllV36Sj0CxR0FkKzZ8tagfQ48cma3dLoHhiXCg0QHQRw8aF5l1N1cfH3czB7KRdaRTcZ6n5UYOa_4GuWDUsKCrfQ.HQcZZN98CzvA82QTgkleEw
  tls: true
  skip-cert-verify: true
  sni: eu1.sec-tunnel.com
- name: Finland-03
  type: http
  server: 77.111.247.79
  port: 443
  username: 4EA6BFF24BB30BECB6450A316FD90589E34A94B3
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJEbGtJUTFlSzRJY2xwX1FtNDNRb2JQQ3FnVkRaN3d1eG9TOVNSSGdVOHlJIiwieSI6Im1fTjVmVXlkaXpHN29iNkJKZnZ5eVoxVWtqY0RzYnFuNnZGS2FvNHhiSjAifX0.xwTL1gScBW7Pywfzd4nWHQcylkKs_jH21TPN0hdoiyymzZ1MCFV84A.WpDXbbhNRV1YzwHp.2OPkVib4oAhPRPGIbaDlWBREyN8mt2SKxwzq7SFDpi5ZVgqUvbJsZ3xMPPpIfrRwt42-mOKGDO80Im8nOY0en3nsq6LGhp90pjrZ4BjjIfXkX6CW-0wQMK5RhMrEUPC2yt6-I1SupN97EBJFb775s0_0z-hPmziwqi1ImKIrp8wHWlZZvD6JlN9Q_vWOMNRleAFjA5psavZlIrIHG5Cz6sJyu0o_GRJXoIKXSM1gQTJxgWX9tn59oecAylKqX08MaNfGXSiL2J1kBgKqvq4myP7eQSCR3dBoBXmiYXq5smCw80j4bc3Wjpnpip-bM0jABxqnORoAn0YtbZb9otFR2pzSlGYFYGFR3vD5mrE9MOFC3pm-TCHcllV36Sj0CxR0FkKzZ8tagfQ48cma3dLoHhiXCg0QHQRw8aF5l1N1cfH3czB7KRdaRTcZ6n5UYOa_4GuWDUsKCrfQ.HQcZZN98CzvA82QTgkleEw
  tls: true
  skip-cert-verify: true
  sni: eu2.sec-tunnel.com
