proxies:
- name: Americas-01
  type: http
  server: 77.111.246.47
  port: 443
  username: D8FA9D37E65C6A9A51E7EF4859A73C3CD047C53A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUam5PSjJWeVk1Ml9kYlhMQUVRY3Voa3luZXlRRFlIbFVSLW5ieEtOZ2VzIiwieSI6InpxZFlWN1FxUlJwUG1CYl9DWDZuc2JpUVlNdlJJcld0eWlweFBYdkhnNVkifX0.ZnXv3ZPRJhv7FPfsmn4SFLN8xJnHZ5b5gzAXSgiy3XjpDi23mIHpzA.Ob-tgHtElCySHBLC.rc17arjFamEpBAJFMKnZ2MLKNEw-j07On96PVZkn814UJSF7XTh-NhDaSW-9QdW-Da8DW7ekFK1g_FqnTiauSHLWcnxO5xEr3xI9aSeNw0H6rodVAgLp-2MpPJ9iuSMS9kIlp2BIhvX2k7BMZxHxbZ-szx5L9qA4h36v4gdo69wWjWKV2pCs1OXjg0GAPVjCaPBOztK6uV-I_BYTwu1TbLa_WFFwy3hfu1YlZTatnePF0gKc4AYw7Cz8o5a01AmgWxs3VoiADE6qf4RXPoD48l5XCaB6HPRCoclOb2nq-U68ucA0WjASOkXlO1VJeDpAUoXv7slr9-uRXoxw1UcMlSpcSeMVA_oB_l5quCA51G0m2OI6TVUQ_Uc3byVIEXZ2MkExl8T5_a1ht2YpJzuhYI56OCYiaoAj-K3_0zleGWU-iJ4X1Gddl7W2N-FvgoxNKqfZSOh5xuE.qBDm8ZEoosYV0nPKX281iA
  tls: true
  skip-cert-verify: true
  sni: am0.sec-tunnel.com
- name: Americas-02
  type: http
  server: 77.111.246.28
  port: 443
  username: D8FA9D37E65C6A9A51E7EF4859A73C3CD047C53A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUam5PSjJWeVk1Ml9kYlhMQUVRY3Voa3luZXlRRFlIbFVSLW5ieEtOZ2VzIiwieSI6InpxZFlWN1FxUlJwUG1CYl9DWDZuc2JpUVlNdlJJcld0eWlweFBYdkhnNVkifX0.ZnXv3ZPRJhv7FPfsmn4SFLN8xJnHZ5b5gzAXSgiy3XjpDi23mIHpzA.Ob-tgHtElCySHBLC.rc17arjFamEpBAJFMKnZ2MLKNEw-j07On96PVZkn814UJSF7XTh-NhDaSW-9QdW-Da8DW7ekFK1g_FqnTiauSHLWcnxO5xEr3xI9aSeNw0H6rodVAgLp-2MpPJ9iuSMS9kIlp2BIhvX2k7BMZxHxbZ-szx5L9qA4h36v4gdo69wWjWKV2pCs1OXjg0GAPVjCaPBOztK6uV-I_BYTwu1TbLa_WFFwy3hfu1YlZTatnePF0gKc4AYw7Cz8o5a01AmgWxs3VoiADE6qf4RXPoD48l5XCaB6HPRCoclOb2nq-U68ucA0WjASOkXlO1VJeDpAUoXv7slr9-uRXoxw1UcMlSpcSeMVA_oB_l5quCA51G0m2OI6TVUQ_Uc3byVIEXZ2MkExl8T5_a1ht2YpJzuhYI56OCYiaoAj-K3_0zleGWU-iJ4X1Gddl7W2N-FvgoxNKqfZSOh5xuE.qBDm8ZEoosYV0nPKX281iA
  tls: true
  skip-cert-verify: true
  sni: am1.sec-tunnel.com
- name: Americas-03
  type: http
  server: 77.111.246.64
  port: 443
  username: D8FA9D37E65C6A9A51E7EF4859A73C3CD047C53A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUam5PSjJWeVk1Ml9kYlhMQUVRY3Voa3luZXlRRFlIbFVSLW5ieEtOZ2VzIiwieSI6InpxZFlWN1FxUlJwUG1CYl9DWDZuc2JpUVlNdlJJcld0eWlweFBYdkhnNVkifX0.ZnXv3ZPRJhv7FPfsmn4SFLN8xJnHZ5b5gzAXSgiy3XjpDi23mIHpzA.Ob-tgHtElCySHBLC.rc17arjFamEpBAJFMKnZ2MLKNEw-j07On96PVZkn814UJSF7XTh-NhDaSW-9QdW-Da8DW7ekFK1g_FqnTiauSHLWcnxO5xEr3xI9aSeNw0H6rodVAgLp-2MpPJ9iuSMS9kIlp2BIhvX2k7BMZxHxbZ-szx5L9qA4h36v4gdo69wWjWKV2pCs1OXjg0GAPVjCaPBOztK6uV-I_BYTwu1TbLa_WFFwy3hfu1YlZTatnePF0gKc4AYw7Cz8o5a01AmgWxs3VoiADE6qf4RXPoD48l5XCaB6HPRCoclOb2nq-U68ucA0WjASOkXlO1VJeDpAUoXv7slr9-uRXoxw1UcMlSpcSeMVA_oB_l5quCA51G0m2OI6TVUQ_Uc3byVIEXZ2MkExl8T5_a1ht2YpJzuhYI56OCYiaoAj-K3_0zleGWU-iJ4X1Gddl7W2N-FvgoxNKqfZSOh5xuE.qBDm8ZEoosYV0nPKX281iA
  tls: true
  skip-cert-verify: true
  sni: am2.sec-tunnel.com
- name: Americas-04
  type: http
  server: 77.111.246.63
  port: 443
  username: D8FA9D37E65C6A9A51E7EF4859A73C3CD047C53A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUam5PSjJWeVk1Ml9kYlhMQUVRY3Voa3luZXlRRFlIbFVSLW5ieEtOZ2VzIiwieSI6InpxZFlWN1FxUlJwUG1CYl9DWDZuc2JpUVlNdlJJcld0eWlweFBYdkhnNVkifX0.ZnXv3ZPRJhv7FPfsmn4SFLN8xJnHZ5b5gzAXSgiy3XjpDi23mIHpzA.Ob-tgHtElCySHBLC.rc17arjFamEpBAJFMKnZ2MLKNEw-j07On96PVZkn814UJSF7XTh-NhDaSW-9QdW-Da8DW7ekFK1g_FqnTiauSHLWcnxO5xEr3xI9aSeNw0H6rodVAgLp-2MpPJ9iuSMS9kIlp2BIhvX2k7BMZxHxbZ-szx5L9qA4h36v4gdo69wWjWKV2pCs1OXjg0GAPVjCaPBOztK6uV-I_BYTwu1TbLa_WFFwy3hfu1YlZTatnePF0gKc4AYw7Cz8o5a01AmgWxs3VoiADE6qf4RXPoD48l5XCaB6HPRCoclOb2nq-U68ucA0WjASOkXlO1VJeDpAUoXv7slr9-uRXoxw1UcMlSpcSeMVA_oB_l5quCA51G0m2OI6TVUQ_Uc3byVIEXZ2MkExl8T5_a1ht2YpJzuhYI56OCYiaoAj-K3_0zleGWU-iJ4X1Gddl7W2N-FvgoxNKqfZSOh5xuE.qBDm8ZEoosYV0nPKX281iA
  tls: true
  skip-cert-verify: true
  sni: am3.sec-tunnel.com
- name: Singapore-01
  type: http
  server: 77.111.245.12
  port: 443
  username: D8FA9D37E65C6A9A51E7EF4859A73C3CD047C53A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUam5PSjJWeVk1Ml9kYlhMQUVRY3Voa3luZXlRRFlIbFVSLW5ieEtOZ2VzIiwieSI6InpxZFlWN1FxUlJwUG1CYl9DWDZuc2JpUVlNdlJJcld0eWlweFBYdkhnNVkifX0.ZnXv3ZPRJhv7FPfsmn4SFLN8xJnHZ5b5gzAXSgiy3XjpDi23mIHpzA.Ob-tgHtElCySHBLC.rc17arjFamEpBAJFMKnZ2MLKNEw-j07On96PVZkn814UJSF7XTh-NhDaSW-9QdW-Da8DW7ekFK1g_FqnTiauSHLWcnxO5xEr3xI9aSeNw0H6rodVAgLp-2MpPJ9iuSMS9kIlp2BIhvX2k7BMZxHxbZ-szx5L9qA4h36v4gdo69wWjWKV2pCs1OXjg0GAPVjCaPBOztK6uV-I_BYTwu1TbLa_WFFwy3hfu1YlZTatnePF0gKc4AYw7Cz8o5a01AmgWxs3VoiADE6qf4RXPoD48l5XCaB6HPRCoclOb2nq-U68ucA0WjASOkXlO1VJeDpAUoXv7slr9-uRXoxw1UcMlSpcSeMVA_oB_l5quCA51G0m2OI6TVUQ_Uc3byVIEXZ2MkExl8T5_a1ht2YpJzuhYI56OCYiaoAj-K3_0zleGWU-iJ4X1Gddl7W2N-FvgoxNKqfZSOh5xuE.qBDm8ZEoosYV0nPKX281iA
  tls: true
  skip-cert-verify: true
  sni: as0.sec-tunnel.com
- name: Singapore-02
  type: http
  server: 77.111.245.13
  port: 443
  username: D8FA9D37E65C6A9A51E7EF4859A73C3CD047C53A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUam5PSjJWeVk1Ml9kYlhMQUVRY3Voa3luZXlRRFlIbFVSLW5ieEtOZ2VzIiwieSI6InpxZFlWN1FxUlJwUG1CYl9DWDZuc2JpUVlNdlJJcld0eWlweFBYdkhnNVkifX0.ZnXv3ZPRJhv7FPfsmn4SFLN8xJnHZ5b5gzAXSgiy3XjpDi23mIHpzA.Ob-tgHtElCySHBLC.rc17arjFamEpBAJFMKnZ2MLKNEw-j07On96PVZkn814UJSF7XTh-NhDaSW-9QdW-Da8DW7ekFK1g_FqnTiauSHLWcnxO5xEr3xI9aSeNw0H6rodVAgLp-2MpPJ9iuSMS9kIlp2BIhvX2k7BMZxHxbZ-szx5L9qA4h36v4gdo69wWjWKV2pCs1OXjg0GAPVjCaPBOztK6uV-I_BYTwu1TbLa_WFFwy3hfu1YlZTatnePF0gKc4AYw7Cz8o5a01AmgWxs3VoiADE6qf4RXPoD48l5XCaB6HPRCoclOb2nq-U68ucA0WjASOkXlO1VJeDpAUoXv7slr9-uRXoxw1UcMlSpcSeMVA_oB_l5quCA51G0m2OI6TVUQ_Uc3byVIEXZ2MkExl8T5_a1ht2YpJzuhYI56OCYiaoAj-K3_0zleGWU-iJ4X1Gddl7W2N-FvgoxNKqfZSOh5xuE.qBDm8ZEoosYV0nPKX281iA
  tls: true
  skip-cert-verify: true
  sni: as1.sec-tunnel.com
- name: Finland-01
  type: http
  server: 77.111.247.79
  port: 443
  username: D8FA9D37E65C6A9A51E7EF4859A73C3CD047C53A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUam5PSjJWeVk1Ml9kYlhMQUVRY3Voa3luZXlRRFlIbFVSLW5ieEtOZ2VzIiwieSI6InpxZFlWN1FxUlJwUG1CYl9DWDZuc2JpUVlNdlJJcld0eWlweFBYdkhnNVkifX0.ZnXv3ZPRJhv7FPfsmn4SFLN8xJnHZ5b5gzAXSgiy3XjpDi23mIHpzA.Ob-tgHtElCySHBLC.rc17arjFamEpBAJFMKnZ2MLKNEw-j07On96PVZkn814UJSF7XTh-NhDaSW-9QdW-Da8DW7ekFK1g_FqnTiauSHLWcnxO5xEr3xI9aSeNw0H6rodVAgLp-2MpPJ9iuSMS9kIlp2BIhvX2k7BMZxHxbZ-szx5L9qA4h36v4gdo69wWjWKV2pCs1OXjg0GAPVjCaPBOztK6uV-I_BYTwu1TbLa_WFFwy3hfu1YlZTatnePF0gKc4AYw7Cz8o5a01AmgWxs3VoiADE6qf4RXPoD48l5XCaB6HPRCoclOb2nq-U68ucA0WjASOkXlO1VJeDpAUoXv7slr9-uRXoxw1UcMlSpcSeMVA_oB_l5quCA51G0m2OI6TVUQ_Uc3byVIEXZ2MkExl8T5_a1ht2YpJzuhYI56OCYiaoAj-K3_0zleGWU-iJ4X1Gddl7W2N-FvgoxNKqfZSOh5xuE.qBDm8ZEoosYV0nPKX281iA
  tls: true
  skip-cert-verify: true
  sni: eu0.sec-tunnel.com
- name: Finland-02
  type: http
  server: 77.111.247.26
  port: 443
  username: D8FA9D37E65C6A9A51E7EF4859A73C3CD047C53A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUam5PSjJWeVk1Ml9kYlhMQUVRY3Voa3luZXlRRFlIbFVSLW5ieEtOZ2VzIiwieSI6InpxZFlWN1FxUlJwUG1CYl9DWDZuc2JpUVlNdlJJcld0eWlweFBYdkhnNVkifX0.ZnXv3ZPRJhv7FPfsmn4SFLN8xJnHZ5b5gzAXSgiy3XjpDi23mIHpzA.Ob-tgHtElCySHBLC.rc17arjFamEpBAJFMKnZ2MLKNEw-j07On96PVZkn814UJSF7XTh-NhDaSW-9QdW-Da8DW7ekFK1g_FqnTiauSHLWcnxO5xEr3xI9aSeNw0H6rodVAgLp-2MpPJ9iuSMS9kIlp2BIhvX2k7BMZxHxbZ-szx5L9qA4h36v4gdo69wWjWKV2pCs1OXjg0GAPVjCaPBOztK6uV-I_BYTwu1TbLa_WFFwy3hfu1YlZTatnePF0gKc4AYw7Cz8o5a01AmgWxs3VoiADE6qf4RXPoD48l5XCaB6HPRCoclOb2nq-U68ucA0WjASOkXlO1VJeDpAUoXv7slr9-uRXoxw1UcMlSpcSeMVA_oB_l5quCA51G0m2OI6TVUQ_Uc3byVIEXZ2MkExl8T5_a1ht2YpJzuhYI56OCYiaoAj-K3_0zleGWU-iJ4X1Gddl7W2N-FvgoxNKqfZSOh5xuE.qBDm8ZEoosYV0nPKX281iA
  tls: true
  skip-cert-verify: true
  sni: eu1.sec-tunnel.com
- name: Finland-03
  type: http
  server: 77.111.244.209
  port: 443
  username: D8FA9D37E65C6A9A51E7EF4859A73C3CD047C53A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUam5PSjJWeVk1Ml9kYlhMQUVRY3Voa3luZXlRRFlIbFVSLW5ieEtOZ2VzIiwieSI6InpxZFlWN1FxUlJwUG1CYl9DWDZuc2JpUVlNdlJJcld0eWlweFBYdkhnNVkifX0.ZnXv3ZPRJhv7FPfsmn4SFLN8xJnHZ5b5gzAXSgiy3XjpDi23mIHpzA.Ob-tgHtElCySHBLC.rc17arjFamEpBAJFMKnZ2MLKNEw-j07On96PVZkn814UJSF7XTh-NhDaSW-9QdW-Da8DW7ekFK1g_FqnTiauSHLWcnxO5xEr3xI9aSeNw0H6rodVAgLp-2MpPJ9iuSMS9kIlp2BIhvX2k7BMZxHxbZ-szx5L9qA4h36v4gdo69wWjWKV2pCs1OXjg0GAPVjCaPBOztK6uV-I_BYTwu1TbLa_WFFwy3hfu1YlZTatnePF0gKc4AYw7Cz8o5a01AmgWxs3VoiADE6qf4RXPoD48l5XCaB6HPRCoclOb2nq-U68ucA0WjASOkXlO1VJeDpAUoXv7slr9-uRXoxw1UcMlSpcSeMVA_oB_l5quCA51G0m2OI6TVUQ_Uc3byVIEXZ2MkExl8T5_a1ht2YpJzuhYI56OCYiaoAj-K3_0zleGWU-iJ4X1Gddl7W2N-FvgoxNKqfZSOh5xuE.qBDm8ZEoosYV0nPKX281iA
  tls: true
  skip-cert-verify: true
  sni: eu2.sec-tunnel.com
- name: Finland-04
  type: http
  server: 77.111.247.80
  port: 443
  username: D8FA9D37E65C6A9A51E7EF4859A73C3CD047C53A
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJUam5PSjJWeVk1Ml9kYlhMQUVRY3Voa3luZXlRRFlIbFVSLW5ieEtOZ2VzIiwieSI6InpxZFlWN1FxUlJwUG1CYl9DWDZuc2JpUVlNdlJJcld0eWlweFBYdkhnNVkifX0.ZnXv3ZPRJhv7FPfsmn4SFLN8xJnHZ5b5gzAXSgiy3XjpDi23mIHpzA.Ob-tgHtElCySHBLC.rc17arjFamEpBAJFMKnZ2MLKNEw-j07On96PVZkn814UJSF7XTh-NhDaSW-9QdW-Da8DW7ekFK1g_FqnTiauSHLWcnxO5xEr3xI9aSeNw0H6rodVAgLp-2MpPJ9iuSMS9kIlp2BIhvX2k7BMZxHxbZ-szx5L9qA4h36v4gdo69wWjWKV2pCs1OXjg0GAPVjCaPBOztK6uV-I_BYTwu1TbLa_WFFwy3hfu1YlZTatnePF0gKc4AYw7Cz8o5a01AmgWxs3VoiADE6qf4RXPoD48l5XCaB6HPRCoclOb2nq-U68ucA0WjASOkXlO1VJeDpAUoXv7slr9-uRXoxw1UcMlSpcSeMVA_oB_l5quCA51G0m2OI6TVUQ_Uc3byVIEXZ2MkExl8T5_a1ht2YpJzuhYI56OCYiaoAj-K3_0zleGWU-iJ4X1Gddl7W2N-FvgoxNKqfZSOh5xuE.qBDm8ZEoosYV0nPKX281iA
  tls: true
  skip-cert-verify: true
  sni: eu3.sec-tunnel.com
