proxies:
- name: Americas-01
  type: http
  server: 77.111.246.25
  port: 443
  username: 5D2FD72F5D72757AB881F4A2EDAB8934D1610E29
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsb2pyOTh0WXZRNF9XRFRCSWJBY3R4QXFESWZEOUZiM3FlcXhHNEw5eS1FIiwieSI6IkJkVUZkcE9ma251RFdCOW9IS3I2SlNFN1M1UDR0dXRIMDNneUF4ZHF0SE0ifX0.PdRYO468mPamd3OZ69L0kSHEh5WkDNWdUO6rsI5jdM8QZ9J7VZLzlQ.Q-Y33_aLOLl127K0.gRu3y25xhdv2_I-eKKPfzGgi_OXvXH8EQ0CpRc0OdvFmYCeqSwhBSjFIjQQt_eHhTJevsX5IjcyJidv_w73fDAcgh-019D_rHvrGm-GHATVW-oor4FEkyzy7SSiGmT9ssWvbcefjOsOEcu2xtrclCRoW8A-VI5FFrh_NRU351rguro14jG7aq5Z8-Y7fgqftX27RU5FJWPxFUbKvGrgEo76JlZU5cshz6jDyDZwqzwiPvUrQpVgRr_QphZWQMryg-J5wFKOwTiX2mpk_564SMwHcCLns5fM6d8X5_MNQa10YqaDh-chKusYOy3d8-60sphEj8awmYhbFVmmkp2oIrxm-wqXFgg3BZ2pu495eluP3qFX0aC4oOLKTGlDBR5gxnkEFcUwtkbYIMBEanJZ2ipT9X9CItjkIr7RTexF26ZLuywDKAE6XK7YbDZKG0WSsRgFd8__s5w.z6l5INss7zH6R1y1uIn1kQ
  tls: true
  skip-cert-verify: true
  sni: am0.sec-tunnel.com
- name: Americas-02
  type: http
  server: 77.111.246.40
  port: 443
  username: 5D2FD72F5D72757AB881F4A2EDAB8934D1610E29
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsb2pyOTh0WXZRNF9XRFRCSWJBY3R4QXFESWZEOUZiM3FlcXhHNEw5eS1FIiwieSI6IkJkVUZkcE9ma251RFdCOW9IS3I2SlNFN1M1UDR0dXRIMDNneUF4ZHF0SE0ifX0.PdRYO468mPamd3OZ69L0kSHEh5WkDNWdUO6rsI5jdM8QZ9J7VZLzlQ.Q-Y33_aLOLl127K0.gRu3y25xhdv2_I-eKKPfzGgi_OXvXH8EQ0CpRc0OdvFmYCeqSwhBSjFIjQQt_eHhTJevsX5IjcyJidv_w73fDAcgh-019D_rHvrGm-GHATVW-oor4FEkyzy7SSiGmT9ssWvbcefjOsOEcu2xtrclCRoW8A-VI5FFrh_NRU351rguro14jG7aq5Z8-Y7fgqftX27RU5FJWPxFUbKvGrgEo76JlZU5cshz6jDyDZwqzwiPvUrQpVgRr_QphZWQMryg-J5wFKOwTiX2mpk_564SMwHcCLns5fM6d8X5_MNQa10YqaDh-chKusYOy3d8-60sphEj8awmYhbFVmmkp2oIrxm-wqXFgg3BZ2pu495eluP3qFX0aC4oOLKTGlDBR5gxnkEFcUwtkbYIMBEanJZ2ipT9X9CItjkIr7RTexF26ZLuywDKAE6XK7YbDZKG0WSsRgFd8__s5w.z6l5INss7zH6R1y1uIn1kQ
  tls: true
  skip-cert-verify: true
  sni: am1.sec-tunnel.com
- name: Americas-03
  type: http
  server: 77.111.246.14
  port: 443
  username: 5D2FD72F5D72757AB881F4A2EDAB8934D1610E29
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsb2pyOTh0WXZRNF9XRFRCSWJBY3R4QXFESWZEOUZiM3FlcXhHNEw5eS1FIiwieSI6IkJkVUZkcE9ma251RFdCOW9IS3I2SlNFN1M1UDR0dXRIMDNneUF4ZHF0SE0ifX0.PdRYO468mPamd3OZ69L0kSHEh5WkDNWdUO6rsI5jdM8QZ9J7VZLzlQ.Q-Y33_aLOLl127K0.gRu3y25xhdv2_I-eKKPfzGgi_OXvXH8EQ0CpRc0OdvFmYCeqSwhBSjFIjQQt_eHhTJevsX5IjcyJidv_w73fDAcgh-019D_rHvrGm-GHATVW-oor4FEkyzy7SSiGmT9ssWvbcefjOsOEcu2xtrclCRoW8A-VI5FFrh_NRU351rguro14jG7aq5Z8-Y7fgqftX27RU5FJWPxFUbKvGrgEo76JlZU5cshz6jDyDZwqzwiPvUrQpVgRr_QphZWQMryg-J5wFKOwTiX2mpk_564SMwHcCLns5fM6d8X5_MNQa10YqaDh-chKusYOy3d8-60sphEj8awmYhbFVmmkp2oIrxm-wqXFgg3BZ2pu495eluP3qFX0aC4oOLKTGlDBR5gxnkEFcUwtkbYIMBEanJZ2ipT9X9CItjkIr7RTexF26ZLuywDKAE6XK7YbDZKG0WSsRgFd8__s5w.z6l5INss7zH6R1y1uIn1kQ
  tls: true
  skip-cert-verify: true
  sni: am2.sec-tunnel.com
- name: Americas-04
  type: http
  server: 77.111.246.60
  port: 443
  username: 5D2FD72F5D72757AB881F4A2EDAB8934D1610E29
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsb2pyOTh0WXZRNF9XRFRCSWJBY3R4QXFESWZEOUZiM3FlcXhHNEw5eS1FIiwieSI6IkJkVUZkcE9ma251RFdCOW9IS3I2SlNFN1M1UDR0dXRIMDNneUF4ZHF0SE0ifX0.PdRYO468mPamd3OZ69L0kSHEh5WkDNWdUO6rsI5jdM8QZ9J7VZLzlQ.Q-Y33_aLOLl127K0.gRu3y25xhdv2_I-eKKPfzGgi_OXvXH8EQ0CpRc0OdvFmYCeqSwhBSjFIjQQt_eHhTJevsX5IjcyJidv_w73fDAcgh-019D_rHvrGm-GHATVW-oor4FEkyzy7SSiGmT9ssWvbcefjOsOEcu2xtrclCRoW8A-VI5FFrh_NRU351rguro14jG7aq5Z8-Y7fgqftX27RU5FJWPxFUbKvGrgEo76JlZU5cshz6jDyDZwqzwiPvUrQpVgRr_QphZWQMryg-J5wFKOwTiX2mpk_564SMwHcCLns5fM6d8X5_MNQa10YqaDh-chKusYOy3d8-60sphEj8awmYhbFVmmkp2oIrxm-wqXFgg3BZ2pu495eluP3qFX0aC4oOLKTGlDBR5gxnkEFcUwtkbYIMBEanJZ2ipT9X9CItjkIr7RTexF26ZLuywDKAE6XK7YbDZKG0WSsRgFd8__s5w.z6l5INss7zH6R1y1uIn1kQ
  tls: true
  skip-cert-verify: true
  sni: am3.sec-tunnel.com
- name: Singapore-01
  type: http
  server: 77.111.245.13
  port: 443
  username: 5D2FD72F5D72757AB881F4A2EDAB8934D1610E29
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsb2pyOTh0WXZRNF9XRFRCSWJBY3R4QXFESWZEOUZiM3FlcXhHNEw5eS1FIiwieSI6IkJkVUZkcE9ma251RFdCOW9IS3I2SlNFN1M1UDR0dXRIMDNneUF4ZHF0SE0ifX0.PdRYO468mPamd3OZ69L0kSHEh5WkDNWdUO6rsI5jdM8QZ9J7VZLzlQ.Q-Y33_aLOLl127K0.gRu3y25xhdv2_I-eKKPfzGgi_OXvXH8EQ0CpRc0OdvFmYCeqSwhBSjFIjQQt_eHhTJevsX5IjcyJidv_w73fDAcgh-019D_rHvrGm-GHATVW-oor4FEkyzy7SSiGmT9ssWvbcefjOsOEcu2xtrclCRoW8A-VI5FFrh_NRU351rguro14jG7aq5Z8-Y7fgqftX27RU5FJWPxFUbKvGrgEo76JlZU5cshz6jDyDZwqzwiPvUrQpVgRr_QphZWQMryg-J5wFKOwTiX2mpk_564SMwHcCLns5fM6d8X5_MNQa10YqaDh-chKusYOy3d8-60sphEj8awmYhbFVmmkp2oIrxm-wqXFgg3BZ2pu495eluP3qFX0aC4oOLKTGlDBR5gxnkEFcUwtkbYIMBEanJZ2ipT9X9CItjkIr7RTexF26ZLuywDKAE6XK7YbDZKG0WSsRgFd8__s5w.z6l5INss7zH6R1y1uIn1kQ
  tls: true
  skip-cert-verify: true
  sni: as0.sec-tunnel.com
- name: Singapore-02
  type: http
  server: 77.111.245.15
  port: 443
  username: 5D2FD72F5D72757AB881F4A2EDAB8934D1610E29
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsb2pyOTh0WXZRNF9XRFRCSWJBY3R4QXFESWZEOUZiM3FlcXhHNEw5eS1FIiwieSI6IkJkVUZkcE9ma251RFdCOW9IS3I2SlNFN1M1UDR0dXRIMDNneUF4ZHF0SE0ifX0.PdRYO468mPamd3OZ69L0kSHEh5WkDNWdUO6rsI5jdM8QZ9J7VZLzlQ.Q-Y33_aLOLl127K0.gRu3y25xhdv2_I-eKKPfzGgi_OXvXH8EQ0CpRc0OdvFmYCeqSwhBSjFIjQQt_eHhTJevsX5IjcyJidv_w73fDAcgh-019D_rHvrGm-GHATVW-oor4FEkyzy7SSiGmT9ssWvbcefjOsOEcu2xtrclCRoW8A-VI5FFrh_NRU351rguro14jG7aq5Z8-Y7fgqftX27RU5FJWPxFUbKvGrgEo76JlZU5cshz6jDyDZwqzwiPvUrQpVgRr_QphZWQMryg-J5wFKOwTiX2mpk_564SMwHcCLns5fM6d8X5_MNQa10YqaDh-chKusYOy3d8-60sphEj8awmYhbFVmmkp2oIrxm-wqXFgg3BZ2pu495eluP3qFX0aC4oOLKTGlDBR5gxnkEFcUwtkbYIMBEanJZ2ipT9X9CItjkIr7RTexF26ZLuywDKAE6XK7YbDZKG0WSsRgFd8__s5w.z6l5INss7zH6R1y1uIn1kQ
  tls: true
  skip-cert-verify: true
  sni: as1.sec-tunnel.com
- name: Finland-01
  type: http
  server: 77.111.247.80
  port: 443
  username: 5D2FD72F5D72757AB881F4A2EDAB8934D1610E29
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsb2pyOTh0WXZRNF9XRFRCSWJBY3R4QXFESWZEOUZiM3FlcXhHNEw5eS1FIiwieSI6IkJkVUZkcE9ma251RFdCOW9IS3I2SlNFN1M1UDR0dXRIMDNneUF4ZHF0SE0ifX0.PdRYO468mPamd3OZ69L0kSHEh5WkDNWdUO6rsI5jdM8QZ9J7VZLzlQ.Q-Y33_aLOLl127K0.gRu3y25xhdv2_I-eKKPfzGgi_OXvXH8EQ0CpRc0OdvFmYCeqSwhBSjFIjQQt_eHhTJevsX5IjcyJidv_w73fDAcgh-019D_rHvrGm-GHATVW-oor4FEkyzy7SSiGmT9ssWvbcefjOsOEcu2xtrclCRoW8A-VI5FFrh_NRU351rguro14jG7aq5Z8-Y7fgqftX27RU5FJWPxFUbKvGrgEo76JlZU5cshz6jDyDZwqzwiPvUrQpVgRr_QphZWQMryg-J5wFKOwTiX2mpk_564SMwHcCLns5fM6d8X5_MNQa10YqaDh-chKusYOy3d8-60sphEj8awmYhbFVmmkp2oIrxm-wqXFgg3BZ2pu495eluP3qFX0aC4oOLKTGlDBR5gxnkEFcUwtkbYIMBEanJZ2ipT9X9CItjkIr7RTexF26ZLuywDKAE6XK7YbDZKG0WSsRgFd8__s5w.z6l5INss7zH6R1y1uIn1kQ
  tls: true
  skip-cert-verify: true
  sni: eu0.sec-tunnel.com
- name: Finland-02
  type: http
  server: 77.111.247.83
  port: 443
  username: 5D2FD72F5D72757AB881F4A2EDAB8934D1610E29
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsb2pyOTh0WXZRNF9XRFRCSWJBY3R4QXFESWZEOUZiM3FlcXhHNEw5eS1FIiwieSI6IkJkVUZkcE9ma251RFdCOW9IS3I2SlNFN1M1UDR0dXRIMDNneUF4ZHF0SE0ifX0.PdRYO468mPamd3OZ69L0kSHEh5WkDNWdUO6rsI5jdM8QZ9J7VZLzlQ.Q-Y33_aLOLl127K0.gRu3y25xhdv2_I-eKKPfzGgi_OXvXH8EQ0CpRc0OdvFmYCeqSwhBSjFIjQQt_eHhTJevsX5IjcyJidv_w73fDAcgh-019D_rHvrGm-GHATVW-oor4FEkyzy7SSiGmT9ssWvbcefjOsOEcu2xtrclCRoW8A-VI5FFrh_NRU351rguro14jG7aq5Z8-Y7fgqftX27RU5FJWPxFUbKvGrgEo76JlZU5cshz6jDyDZwqzwiPvUrQpVgRr_QphZWQMryg-J5wFKOwTiX2mpk_564SMwHcCLns5fM6d8X5_MNQa10YqaDh-chKusYOy3d8-60sphEj8awmYhbFVmmkp2oIrxm-wqXFgg3BZ2pu495eluP3qFX0aC4oOLKTGlDBR5gxnkEFcUwtkbYIMBEanJZ2ipT9X9CItjkIr7RTexF26ZLuywDKAE6XK7YbDZKG0WSsRgFd8__s5w.z6l5INss7zH6R1y1uIn1kQ
  tls: true
  skip-cert-verify: true
  sni: eu1.sec-tunnel.com
- name: Finland-03
  type: http
  server: 77.111.244.210
  port: 443
  username: 5D2FD72F5D72757AB881F4A2EDAB8934D1610E29
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsb2pyOTh0WXZRNF9XRFRCSWJBY3R4QXFESWZEOUZiM3FlcXhHNEw5eS1FIiwieSI6IkJkVUZkcE9ma251RFdCOW9IS3I2SlNFN1M1UDR0dXRIMDNneUF4ZHF0SE0ifX0.PdRYO468mPamd3OZ69L0kSHEh5WkDNWdUO6rsI5jdM8QZ9J7VZLzlQ.Q-Y33_aLOLl127K0.gRu3y25xhdv2_I-eKKPfzGgi_OXvXH8EQ0CpRc0OdvFmYCeqSwhBSjFIjQQt_eHhTJevsX5IjcyJidv_w73fDAcgh-019D_rHvrGm-GHATVW-oor4FEkyzy7SSiGmT9ssWvbcefjOsOEcu2xtrclCRoW8A-VI5FFrh_NRU351rguro14jG7aq5Z8-Y7fgqftX27RU5FJWPxFUbKvGrgEo76JlZU5cshz6jDyDZwqzwiPvUrQpVgRr_QphZWQMryg-J5wFKOwTiX2mpk_564SMwHcCLns5fM6d8X5_MNQa10YqaDh-chKusYOy3d8-60sphEj8awmYhbFVmmkp2oIrxm-wqXFgg3BZ2pu495eluP3qFX0aC4oOLKTGlDBR5gxnkEFcUwtkbYIMBEanJZ2ipT9X9CItjkIr7RTexF26ZLuywDKAE6XK7YbDZKG0WSsRgFd8__s5w.z6l5INss7zH6R1y1uIn1kQ
  tls: true
  skip-cert-verify: true
  sni: eu2.sec-tunnel.com
- name: Finland-04
  type: http
  server: 77.111.247.76
  port: 443
  username: 5D2FD72F5D72757AB881F4A2EDAB8934D1610E29
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJsb2pyOTh0WXZRNF9XRFRCSWJBY3R4QXFESWZEOUZiM3FlcXhHNEw5eS1FIiwieSI6IkJkVUZkcE9ma251RFdCOW9IS3I2SlNFN1M1UDR0dXRIMDNneUF4ZHF0SE0ifX0.PdRYO468mPamd3OZ69L0kSHEh5WkDNWdUO6rsI5jdM8QZ9J7VZLzlQ.Q-Y33_aLOLl127K0.gRu3y25xhdv2_I-eKKPfzGgi_OXvXH8EQ0CpRc0OdvFmYCeqSwhBSjFIjQQt_eHhTJevsX5IjcyJidv_w73fDAcgh-019D_rHvrGm-GHATVW-oor4FEkyzy7SSiGmT9ssWvbcefjOsOEcu2xtrclCRoW8A-VI5FFrh_NRU351rguro14jG7aq5Z8-Y7fgqftX27RU5FJWPxFUbKvGrgEo76JlZU5cshz6jDyDZwqzwiPvUrQpVgRr_QphZWQMryg-J5wFKOwTiX2mpk_564SMwHcCLns5fM6d8X5_MNQa10YqaDh-chKusYOy3d8-60sphEj8awmYhbFVmmkp2oIrxm-wqXFgg3BZ2pu495eluP3qFX0aC4oOLKTGlDBR5gxnkEFcUwtkbYIMBEanJZ2ipT9X9CItjkIr7RTexF26ZLuywDKAE6XK7YbDZKG0WSsRgFd8__s5w.z6l5INss7zH6R1y1uIn1kQ
  tls: true
  skip-cert-verify: true
  sni: eu3.sec-tunnel.com
