proxies:
- name: hos
  type: http
  server: ip_address
  port: 443
  username: 799725DD96791685BDD39B8EBD25248C6E7CC73F
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBZDUtc2dwazFZbkFqb0drQTh6NTUwcGNRNWZZV3BfV1owWE9lZzdsTFhnIiwieSI6IlNTdUxhcVUwREU4SmtDcGVBajc1bXFvNk01UjBIZk1hcDZQeVpHckp2SUEifX0.3CZtjptlrWqE-wnxyLBT_LHpsXCfB9HWcPyhRWkxomXP8xe6EIOj2A.dVcuvWMc5LBGAhGU.VH1wBrhrQLNxbLVYjtGnGaX2t3QXLdmU1xkETbHtN3xhunQmoH5RdZNuFc4s8Cdrlk_IbeiZiMBpuqwdr9l_-owzNTx8zPlX9byn1-LrHVhBSHb3E0-7BYoyw94vHUC8Lp7UFLEEhPX6Qy8Chw0IxR7at_DIMIPc4bnAAnwzDcpRPUvzDdC11FzLGoZ1PiVlssT8b_SReKLYLj2KbWqrcR305sTT8jge_KqvLft0MH1qBermIFhfZMdsKTyrSrkRVApo6hb4Njn7p0PwPGe2giUX0NRT8ThcS6HVcDJVu1s5SeXZY5Y4ID3ZzvEM9z48UUoIg4fcBpaJl6KJ6c3VvLXze3QrCsRe2cDJgpMLgpv0HTeK2BYH0BlOnRZy3hZSWtBy3Yn27fogVq-_54P3yx7eXC3Hwazovt_peogvE1J26iyei2fxhLbSMJ6ToRataILaQA0lr3s.LOJfmeE1Jrx4i4vHlRYuiw
  tls: true
  skip-cert-verify: false
  sni: host

- name: eu0
  type: http
  server: 77.111.247.21
  port: 443
  username: 799725DD96791685BDD39B8EBD25248C6E7CC73F
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBZDUtc2dwazFZbkFqb0drQTh6NTUwcGNRNWZZV3BfV1owWE9lZzdsTFhnIiwieSI6IlNTdUxhcVUwREU4SmtDcGVBajc1bXFvNk01UjBIZk1hcDZQeVpHckp2SUEifX0.3CZtjptlrWqE-wnxyLBT_LHpsXCfB9HWcPyhRWkxomXP8xe6EIOj2A.dVcuvWMc5LBGAhGU.VH1wBrhrQLNxbLVYjtGnGaX2t3QXLdmU1xkETbHtN3xhunQmoH5RdZNuFc4s8Cdrlk_IbeiZiMBpuqwdr9l_-owzNTx8zPlX9byn1-LrHVhBSHb3E0-7BYoyw94vHUC8Lp7UFLEEhPX6Qy8Chw0IxR7at_DIMIPc4bnAAnwzDcpRPUvzDdC11FzLGoZ1PiVlssT8b_SReKLYLj2KbWqrcR305sTT8jge_KqvLft0MH1qBermIFhfZMdsKTyrSrkRVApo6hb4Njn7p0PwPGe2giUX0NRT8ThcS6HVcDJVu1s5SeXZY5Y4ID3ZzvEM9z48UUoIg4fcBpaJl6KJ6c3VvLXze3QrCsRe2cDJgpMLgpv0HTeK2BYH0BlOnRZy3hZSWtBy3Yn27fogVq-_54P3yx7eXC3Hwazovt_peogvE1J26iyei2fxhLbSMJ6ToRataILaQA0lr3s.LOJfmeE1Jrx4i4vHlRYuiw
  tls: true
  skip-cert-verify: false
  sni: eu0.sec-tunnel.com

- name: eu1
  type: http
  server: 77.111.247.57
  port: 443
  username: 799725DD96791685BDD39B8EBD25248C6E7CC73F
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBZDUtc2dwazFZbkFqb0drQTh6NTUwcGNRNWZZV3BfV1owWE9lZzdsTFhnIiwieSI6IlNTdUxhcVUwREU4SmtDcGVBajc1bXFvNk01UjBIZk1hcDZQeVpHckp2SUEifX0.3CZtjptlrWqE-wnxyLBT_LHpsXCfB9HWcPyhRWkxomXP8xe6EIOj2A.dVcuvWMc5LBGAhGU.VH1wBrhrQLNxbLVYjtGnGaX2t3QXLdmU1xkETbHtN3xhunQmoH5RdZNuFc4s8Cdrlk_IbeiZiMBpuqwdr9l_-owzNTx8zPlX9byn1-LrHVhBSHb3E0-7BYoyw94vHUC8Lp7UFLEEhPX6Qy8Chw0IxR7at_DIMIPc4bnAAnwzDcpRPUvzDdC11FzLGoZ1PiVlssT8b_SReKLYLj2KbWqrcR305sTT8jge_KqvLft0MH1qBermIFhfZMdsKTyrSrkRVApo6hb4Njn7p0PwPGe2giUX0NRT8ThcS6HVcDJVu1s5SeXZY5Y4ID3ZzvEM9z48UUoIg4fcBpaJl6KJ6c3VvLXze3QrCsRe2cDJgpMLgpv0HTeK2BYH0BlOnRZy3hZSWtBy3Yn27fogVq-_54P3yx7eXC3Hwazovt_peogvE1J26iyei2fxhLbSMJ6ToRataILaQA0lr3s.LOJfmeE1Jrx4i4vHlRYuiw
  tls: true
  skip-cert-verify: false
  sni: eu1.sec-tunnel.com

- name: eu2
  type: http
  server: 77.111.247.55
  port: 443
  username: 799725DD96791685BDD39B8EBD25248C6E7CC73F
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBZDUtc2dwazFZbkFqb0drQTh6NTUwcGNRNWZZV3BfV1owWE9lZzdsTFhnIiwieSI6IlNTdUxhcVUwREU4SmtDcGVBajc1bXFvNk01UjBIZk1hcDZQeVpHckp2SUEifX0.3CZtjptlrWqE-wnxyLBT_LHpsXCfB9HWcPyhRWkxomXP8xe6EIOj2A.dVcuvWMc5LBGAhGU.VH1wBrhrQLNxbLVYjtGnGaX2t3QXLdmU1xkETbHtN3xhunQmoH5RdZNuFc4s8Cdrlk_IbeiZiMBpuqwdr9l_-owzNTx8zPlX9byn1-LrHVhBSHb3E0-7BYoyw94vHUC8Lp7UFLEEhPX6Qy8Chw0IxR7at_DIMIPc4bnAAnwzDcpRPUvzDdC11FzLGoZ1PiVlssT8b_SReKLYLj2KbWqrcR305sTT8jge_KqvLft0MH1qBermIFhfZMdsKTyrSrkRVApo6hb4Njn7p0PwPGe2giUX0NRT8ThcS6HVcDJVu1s5SeXZY5Y4ID3ZzvEM9z48UUoIg4fcBpaJl6KJ6c3VvLXze3QrCsRe2cDJgpMLgpv0HTeK2BYH0BlOnRZy3hZSWtBy3Yn27fogVq-_54P3yx7eXC3Hwazovt_peogvE1J26iyei2fxhLbSMJ6ToRataILaQA0lr3s.LOJfmeE1Jrx4i4vHlRYuiw
  tls: true
  skip-cert-verify: false
  sni: eu2.sec-tunnel.com

- name: eu3
  type: http
  server: 77.111.247.61
  port: 443
  username: 799725DD96791685BDD39B8EBD25248C6E7CC73F
  password: eyJhbGciOiJFQ0RILUVTK0EyNTZLVyIsImN0eSI6IkpXVCIsImVuYyI6IkEyNTZHQ00iLCJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJBZDUtc2dwazFZbkFqb0drQTh6NTUwcGNRNWZZV3BfV1owWE9lZzdsTFhnIiwieSI6IlNTdUxhcVUwREU4SmtDcGVBajc1bXFvNk01UjBIZk1hcDZQeVpHckp2SUEifX0.3CZtjptlrWqE-wnxyLBT_LHpsXCfB9HWcPyhRWkxomXP8xe6EIOj2A.dVcuvWMc5LBGAhGU.VH1wBrhrQLNxbLVYjtGnGaX2t3QXLdmU1xkETbHtN3xhunQmoH5RdZNuFc4s8Cdrlk_IbeiZiMBpuqwdr9l_-owzNTx8zPlX9byn1-LrHVhBSHb3E0-7BYoyw94vHUC8Lp7UFLEEhPX6Qy8Chw0IxR7at_DIMIPc4bnAAnwzDcpRPUvzDdC11FzLGoZ1PiVlssT8b_SReKLYLj2KbWqrcR305sTT8jge_KqvLft0MH1qBermIFhfZMdsKTyrSrkRVApo6hb4Njn7p0PwPGe2giUX0NRT8ThcS6HVcDJVu1s5SeXZY5Y4ID3ZzvEM9z48UUoIg4fcBpaJl6KJ6c3VvLXze3QrCsRe2cDJgpMLgpv0HTeK2BYH0BlOnRZy3hZSWtBy3Yn27fogVq-_54P3yx7eXC3Hwazovt_peogvE1J26iyei2fxhLbSMJ6ToRataILaQA0lr3s.LOJfmeE1Jrx4i4vHlRYuiw
  tls: true
  skip-cert-verify: false
  sni: eu3.sec-tunnel.com

