name: Opera Proxy to Clash Config

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次

permissions:
  contents: write  # 添加创建 release 的权限

jobs:
  generate-config:
    runs-on: ubuntu-latest

    steps:
      - name: Get current time
        id: current-time
        run: echo "time=$(date -u +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Download opera-proxy
        run: |
          wget https://github.com/Snawoot/opera-proxy/releases/download/v1.11.2/opera-proxy.linux-amd64 -O opera-proxy
          chmod +x opera-proxy

      - name: Generate proxy list
        id: proxy-gen
        run: |
          # 运行命令并捕获输出
          OUTPUT=$(./opera-proxy -country EU -list-proxies)
          
          # 解析输出
          PROXY_LOGIN=$(echo "$OUTPUT" | grep "Proxy login:" | cut -d ' ' -f 3)
          PROXY_PASS=$(echo "$OUTPUT" | grep "Proxy password:" | cut -d ' ' -f 3)
          
          # 创建 clash 配置文件
          echo "proxies:" > clash-config.yml
          
          # 处理每个代理服务器
          echo "$OUTPUT" | grep -E "^[^,]+,[^,]+,[^,]+$" | while IFS=, read -r host ip port; do
            # 获取域名的前三个字母
            NAME_PREFIX=$(echo $host | cut -c1-3)
            
            # 添加代理配置
            echo "- name: ${NAME_PREFIX}" >> clash-config.yml
            echo "  type: http" >> clash-config.yml
            echo "  server: ${host}" >> clash-config.yml
            echo "  port: ${port}" >> clash-config.yml
            echo "  username: ${PROXY_LOGIN}" >> clash-config.yml
            echo "  password: ${PROXY_PASS}" >> clash-config.yml
            echo "  tls: true" >> clash-config.yml
            echo "  skip-cert-verify: false" >> clash-config.yml
            echo "  sni: ${host}" >> clash-config.yml
            echo "" >> clash-config.yml
          done

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: clash-config.yml
          name: "Proxy Config ${{ steps.current-time.outputs.time }}"
          tag_name: "proxy-${{ steps.current-time.outputs.time }}"
          body: "Proxy configuration updated at ${{ steps.current-time.outputs.time }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
