name: Generate Opera Proxy Config

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次

jobs:
  generate-proxy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download opera-proxy
        run: |
          wget https://github.com/Snawoot/opera-proxy/releases/download/v1.11.2/opera-proxy.linux-amd64 -O opera-proxy
          chmod +x opera-proxy

      - name: Generate proxy list
        run: |
          # 运行命令并捕获输出
          OUTPUT=$(./opera-proxy -country EU -list-proxies)
          
          # 解析输出
          PROXY_LOGIN=$(echo "$OUTPUT" | grep "Proxy login:" | cut -d ' ' -f 3)
          PROXY_PASS=$(echo "$OUTPUT" | grep "Proxy password:" | cut -d ' ' -f 3)
          
          # 创建clash配置文件
          echo "proxies:" > clash-config.yml
          
          # 处理每个代理服务器
          echo "$OUTPUT" | grep -E "^[^,]+,[^,]+,[^,]+$" | while IFS=, read -r host ip port; do
            # 获取域名的前三个字母
            NAME_PREFIX=$(echo $host | cut -c1-3)
            
            # 添加代理配置
            echo "- name: ${NAME_PREFIX}" >> clash-config.yml
            echo "  type: http" >> clash-config.yml
            echo "  server: ${host}" >> clash-config.yml
            echo "  port: ${port}" >> clash-config.yml
            echo "  username: ${PROXY_LOGIN}" >> clash-config.yml
            echo "  password: ${PROXY_PASS}" >> clash-config.yml
            echo "  tls: true" >> clash-config.yml
            echo "  skip-cert-verify: false" >> clash-config.yml
            echo "  sni: ${host}" >> clash-config.yml
            echo "" >> clash-config.yml
          done

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add clash-config.yml
          git commit -m "Update proxy configuration $(date +%Y-%m-%d_%H-%M-%S)"
          git push
